### ISSUE TITLE
Stop detection while hand is in movement

### ISSUE THREAD

**Issue by DanielMy777** [DanielMy777/Signify#107]
The camera app sends a frame for detection every 1 second.
Sometimes, the hand is in movement (the person is preparing for something), we do not want to detect thet. 
We only want to detect when the hand is still.
This can be achieved in the cameraApp by tracing the last bounding boxes from frame to frame. If the distance between the boxes is large, the hand is in movement.

**Comment by DanielMy777** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!
Most important issue right now!!!
We all need to invoke into it.
@chai00xxdd please tell us when u can sit on this and we will come help u until we get it done.

**Comment by chai00xxdd** [comment]
i will sit on in from tomorow i guess

**Comment by DanielMy777** [comment]
I will join.
I will do your complexity test if u get this

**Comment by DanielMy777** [comment]
Done for words.
Too slow for letters
