### ISSUE TITLE
Fix doubling

### ISSUE THREAD

**Issue by DanielMy777** [DanielMy777/Signify#111]
Its bad that one hand gesture can be detected twice.
If the same letter is detected twice, don't show it on screen.
If its detected a third time, show it on screen as the second detection.
(Yes, you will have to hold your hand for a bit of a long time to do a double letter, but that's ok)
This should fix the problem, because a letter will be detected twice only if the user REALLY wants to.

If the letter is detected for a 4,5,6+ times, do not show it on screen as a detection. there's no word with 3 same letters in a row.

**Comment by chai00xxdd** [comment]
sure #117

**Comment by DanielMy777** [comment]
Done.
