### ISSUE TITLE
Do not speak same word / letter if not written

### ISSUE THREAD

**Issue by DanielMy777** [DanielMy777/Signify#157]
Seems weird, you expect it to be written.

**Comment by chai00xxdd** [comment]
?

**Comment by DanielMy777** [comment]
Done, right? @chai00xxdd

**Comment by chai00xxdd** [comment]
not sure the problem

**Comment by DanielMy777** [comment]
for instance,
when the word 'hamburger' is detected twice in a row, the app will say 'hamburger' twice, but will only write it once.
It used to look weird, u should just speak a word only if its written.
