### ISSUE TITLE
Stabilizethe hand rectangle (react app side)

### ISSUE THREAD

**Issue by chai00xxdd** [DanielMy777/Signify#45]
right now, the rectangle behinde the hands is update
x times in a seconds what makes the rectangle beside the hands update each time
but sometimes the update is minor (the hand moves a little bit) so we can stay with the previous rectangle.
this is needed cus right now its looks wired every small movemnt even by the angle the camera a new rectangle is returned from the server what gives wired looks to it.
for example: the first rectangle start in x = 10
and the second one start in x = 11
the third one x = 10 and so on....
insted update all the time we can stay with the first one what will give it smoth looks

**Comment by DanielMy777** [comment]
This is done isnt it?

**Comment by chai00xxdd** [comment]
in my phone yes ( how it works on yours?)

**Comment by DanielMy777** [comment]
Works great, 
just wanted to know if we can close this.
