### ISSUE TITLE
Learning page

### ISSUE THREAD

**Issue by DanielMy777** [DanielMy777/Signify#82]
A page needs to be created, it has to hold place for a textbox, in which the user can enter a word and submit it.
An animation of the spelling in sign language will present itself underneath.
(The animation should just be a simple fade transition between the letter images)

**Comment by chai00xxdd** [comment]
i want to kill my self

**Comment by DanielMy777** [comment]
> i want to kill my self

ok m80

**Comment by DanielMy777** [comment]
can be closed
